export const ERROR_CODES = {
  AUTH: {
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  },

  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    INACTIVE: 'USER_INACTIVE',
    DELETED: 'USER_DELETED',
    ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  },

  VALIDATION: {
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
    EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  },

  DATABASE: {
    CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
    QUERY_FAILED: 'DB_QUERY_FAILED',
    DUPLICATE_ENTRY: 'DB_DUPLICATE_ENTRY',
    RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  },

  SERVER: {
    INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    TIMEOUT: 'REQUEST_TIMEOUT',
  },

  REQUEST: {
    BAD_REQUEST: 'BAD_REQUEST',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  },

  PERMISSIONS: {
    NOT_ALLOWED: 'PERMISSION_DENIED',
    ROLE_REQUIRED: 'ROLE_REQUIRED',
  },

  FILE: {
    UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
    INVALID_FORMAT: 'INVALID_FILE_FORMAT',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    NOT_FOUND: 'FILE_NOT_FOUND',
  },

  PAYMENT: {
    FAILED: 'PAYMENT_FAILED',
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  },

  THIRD_PARTY: {
    API_ERROR: 'EXTERNAL_API_ERROR',
    SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  },
};
